/*
 * This file is generated by jOOQ.
 */
package org.example.jooq;


import org.example.jooq.tables.Article;
import org.example.jooq.tables.Author;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.article</code>.
     */
    public static final Article ARTICLE = Article.ARTICLE;

    /**
     * The table <code>public.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;
}
